---
title: ""
author: ""
date: ""
font: Lato
output:
  html_document:
    self_contained: TRUE
    toc: TRUE
    toc_float: TRUE
    css: www/web_report.css
    mathjax: null
    editor_options:
      chunk_output_type: console
params:
  state_county: !r c("51013", "06037", "53033", "36061")
---

# Key Predictors and Metrics

## Strong and Healthy Families

### Domain: Financial Well-Being {#domain-financial-well-being}

##### PREDICTOR: INCOME

**Metric: Household income at the 20th, 50th, and 80th percentiles**

Household income is a standard measure of financial well-being. The Working Group recommended the metrics at these three levels to track how and for whom incomes are changing in a given place as well as whether incomes are rising across the board or more so for those with higher incomes. To identify income percentiles, all households are ranked by income from lowest to highest. The income level at the threshold between the poorest 20 percent of households and the richest 80 percent is the 20th percentile. Similarly, the threshold between the poorest and richest halves is the 50th percentile (or median), and threshold between the poorest 80 percent and richest 20 percent is the 80th percentile. 

**Validity:** These are well-established and frequently used measures to assess the financial well-being of families by several federal agencies and many scholars.

**Availability:** Data on household income are available annually from the Census Bureau’s American Community Survey (ACS).

**Frequency:** Survey data are collected annually and used to create 1- and 5-year estimates. For subgroup analyses for less populated areas, it may be necessary to pool several years of data to obtain reliable estimates.

**Geography:** Data are available at the county and metro levels.

**Consistency:** Income data in the ACS are measured the same way across all geographies in the same year. The measure is fairly consistent over time but there could be changes in the phrasing and sequence of income source questions that may affect comparisons over time. When such changes have occurred in other federal surveys, such as the Current Population Survey, the Census Bureau provides bridge year data so users can assess the effects of survey changes.

**Subgroups:** The data can be broken down by race or ethnicity, gender, and other demographic factors. For less populous areas and for certain demographic groups, several years of data may need to be pooled to provide reliable estimates. 

**Limitations:** The purchasing power of any particular level of income will vary based on the local cost of living. Also, because household sizes differ, the same income may be stretched across larger average households in some places relative to others. Like all metrics based on the characteristics of people living in an area, it can change because of residential mobility. 

<br>

##### PREDICTOR: FINANCIAL SECURITY

**Metric: Share with debt in collections**

The measure accounts for the share of people with a credit bureau record in an area with debt that has progressed from being past due to being in collections. Debt in collections includes past-due credit lines that have been closed and charged-off on the creditor’s books as well as unpaid bills reported to the credit bureaus that the creditor is attempting to collect. For example, credit card accounts enter collections once they are 180 days past due. Retail installment loans are retail purchases with installment terms—for example, a loan from a furniture store to buy a couch.

**Validity:** Families without other accessible financial resources may need to take out debt not only to pay for housing or education but also to pay for daily necessities such as food or utilities. The inability to pay back debts can signal current or near-term financial insecurity, particularly for families with lower incomes. Those households likely have few assets and as such may have negative wealth. Though not a standard measure, this metric has been used by researchers to distinguish between “good” debts (e.g. mortgages paid on time every month) and “bad” debts (Braga et al. 2016; Ratcliffe et al. 2014).

**Availability:** Drawn directly from credit reports, the credit bureau data are national and uniform across the country. The data are restricted and are not accessible directly from credit bureaus but are made available publicly on the Urban Institute's [Debt in America website](https://apps.urban.org/features/debt-interactive-map/?type=overall&variable=pct_debt_collections). 

**Frequency:** These data can be updated annually. 

**Geography:** The share of households with debt in collections can be computed by zip code or county 

**Consistency:** The share of households with debt in collections can be measured consistently for all geographies. The measure is likely to remain consistent over time, unless the credit bureaus change the way overdue debt is captured in credit reporting. 

**Subgroups:** The credit bureau data do not include information about race, so the white and people of color metrics are based on the racial makeup of zip codes within the geographic area (US, state, county). Specifically, the majority-white communities are based on credit records for people who live in zip codes where most residents are white (at least 60 percent of the population is white), and communities of color values are based on credit records for people who live in zip codes where most residents are people of color (at least 60 percent of the population is African American, Hispanic, Asian or Pacific Islander, American Indian or Alaska Native, another race other than white, or multiracial). The ACS data include information on people’s race, so the white and people of color values for ACS metrics are calculated directly for those populations. 

**Limitations:** Aside from the limitations related to geography and subgroup analysis, these data do not capture “credit invisible” households without a credit record. And as a measure of financial well-being, even if few households have debt in collections, many may still have too little wealth or savings to be primed for upward mobility. This measure is somewhat sensitive to resident turnover. If a large number of residents without overdue debt move into a county or zip code, or if a large number of residents with overdue debt move out, this measure could shift without any in-household change in debt management.

<br>

### Domain: Secure and Stable Housing {#domain-housing}

##### PREDICTOR: AFFORDABLE HOUSING 

**Metric: Ratio of affordable and available housing units to households with low- and very low–income levels**

This metric reports the number of available housing units affordable for households with low- (below 80 percent of area median income, or AMI), very low- (below 50 percent of AMI), and extremely low- (below 30 percent of AMI) incomes relative to the number of households with these income levels. Housing units are defined as affordable if the monthly costs do not exceed 30 percent of a household’s income. For this metric, the stock of available housing units includes both vacant and occupied units and both rental and homeowner units. A unit is considered available for households at a given level of income if its monthly cost is affordable at that income level—regardless of the income of the current occupant.

**Validity:** Affordable housing ratios of this type are widely applied in studies of local housing market conditions and trends (Getsinger et al. 2017; Turner et al. 2019). Both the income categories and the affordability standard are well established and accepted in both research and policy.

**Availability:** These ratios can be constructed using data from the American Community Survey (ACS) and income categories defined by the US Department of Housing and Urban Development, both of which are publicly available nationwide.

**Frequency:** These ratios can be updated annually.

**Geography:** Affordable housing ratios can be computed by city or county. For less populous areas, it may be necessary to pool multiple years of data and report moving averages. 

**Consistency:** Affordable housing ratios can be computed consistently for all counties and cities over time. Because the income categories are calculated relative to AMI, the affordability metric appropriately reflects local economic conditions. 

**Subgroups:** Because these ratios focus on the characteristics of the housing stock, stratifying by demographic subgroups is not relevant. However, housing units in each affordability category can be stratified by size (number of bedrooms) and tenure (owned or rented).

**Limitations:** These shares do not reflect the quality of the available and affordable housing units. Units counted as available and affordable for households with low or very low incomes may be poor quality or too small to meet household needs. This metric is somewhat sensitive to patterns of residential mobility. For example, if the number of households with very low incomes were to decline (because of out-migration), this metric would show improvement even if no additional affordable units were produced.

<br>

##### PREDICTOR: HOUSING INSTABILITY AND HOMELESSNESS 

**Metric: Number of public school children who are ever homeless during the school year**

This metric identifies the number of children (age 3 through 12th grade) who are enrolled in public schools and whose primary nighttime residence at any time during a school year was a shelter, transitional housing, or awaiting foster care placement; unsheltered (e.g., a car, park, campground, temporary trailer, or abandoned building); a hotel or motel because of the lack of alternative adequate accommodations; or in housing of other people because of loss of housing, economic hardship, or a similar reason. 

**Validity:** Data are reported by school administrators and generally verified by local liaisons and state coordinators. This is a direct and well-established measure of homelessness for children that results from and reflects housing instability among families and unaccompanied children. The definition of homelessness used for this measure extends beyond literal homelessness to effectively include the full range of circumstances in which a family does not have a stable home of their own.

**Availability:** The US Department of Education requires every local education agency to collect and report these data.

**Frequency:** This measure is produced annually.

**Geography:** The boundaries of local education agencies can be crosswalked to the city and county levels. 

**Consistency:** This measure is consistently defined, collected, and reported for all local education agencies nationwide.

**Subgroups:** This metric can be disaggregated based on students’ disability status and whether they are enrolled in English-as–a-second-language courses.

**Limitations:** This measure does not include homeless adults who are childless, and it does not capture homelessness among children who do not enroll in public school. Further, it could show improvement if the families of homeless children move to a neighboring jurisdiction or if policies “push” them out. This metric is quite sensitive to patterns of residential mobility if large numbers of families with very low incomes flow into or out of a local education agency’s boundary.

<br>

### Domain: Family Stability {#domain-family-stability}

##### PREDICTOR: FAMILY STRUCTURE AND STABILITY 

**Metric: Share of children in various family living arrangement**

The Working Group advised considering the share of children living in each of six different living arrangements (that sum to 100 percent): two married biological or adoptive parents; one biological or adoptive parent and that parent’s current spouse or partner; one biological or adoptive parent and at least one other adult; one biological or adoptive parent; at least two adults, but no parent; and all other.

**Validity:** Children’s living arrangements are recorded in household rosters used in several federal datasets.

**Availability:** Data on living arrangements are available annually from the Census Bureau’s American Community Survey (ACS).

**Frequency:** Survey data are collected annually and used to create 1- and 5-year estimates. For subgroup analyses for less populated areas, it may be necessary to pool several years of data to obtain reliable estimates.

**Geography:** Data are available at the county and metro levels.

**Consistency:** Data on children’s living arrangements in the ACS are measured the same way across all geographies in the same year. The measure is consistent over time.

**Subgroups:** The data can be broken down by race or ethnicity, gender, and other demographic factors. For less populous areas and for certain demographic groups, several years of data may need to be pooled to provide reliable estimates. 

**Limitations:** A large body of evidence suggests that both the presence and relationship of parents directly relates to children’s mobility (Chetty et al. 2014; McLanahan and Percheski 2008; Osborne and McLanahan 2007). Ideally, the metric would directly reflect the continuous presence of loving adults in a child’s life. But data to construct such a measure are not consistently available at the city or county level. We recommended a metric detailing children’s living arrangements. Further, research shows that the influence of growing up in a single-parent household on later economic outcomes has been diminishing over the past few decades (Musick and Mare 2004), and some research suggests that the strength of the relationship between married parents and child outcomes is much stronger for white children than for children of color (Cross 2019). Like all metrics based on the characteristics of people living in an area, it can change because of residential mobility.

<br>

### Domain: Health {#domain-health}

##### PREDICTOR: OVERALL HEALTH 

**Metric: Share of adults who rate their own and their children’s health as good or excellent**

This metric is measured through one question that asks “How would you rate your health?” and has respondents answer along a five-point Likert scale of “very poor,” “poor,” “fair,” “good,” and “excellent” (Eriksson, Undén, and Elofsson 2001). The share of people who respond “good” or “excellent” constitutes this metric. 

**Validity:** Asking people to rate their own health provides one of the most reliable measures of mortality and remains a significant predictor even after controlling for other demonstrated health-related issues and socioeconomic status (DeSalvo et al. 2006; Garbarski 2014; Herman et al. 2014; Idler and Benyamini 1997). Though the research focuses on mortality rather than mobility, we argue that good health is a condition that supports autonomy and promotes mobility. 

**Availability:** This information is not widely enough available in existing data sources to provide coverage at the local level across many geographies. 

**Frequency:** The frequency of how often the measure would be collected would depend upon local data collection efforts, but we recommend regular follow-up data collection at least every two years.

**Geography:** The level of geography that the measure would represent (e.g., county, city, or zip code) would depend on the sampling frame, stratification, and the number of people ultimately surveyed to obtain sufficient power for the survey. 

**Consistency:** Self-rated health can be consistently defined and determined over time. The degree of consistency in this measure across different places will vary with the extensiveness of the survey design and number of people surveyed in each place. Ideally, the measure could be consistent across some base level of geography (such as the city or county), but some places would likely have more extensive coverage of self-rated health.

**Subgroups:** Like geography, the range of subgroups represented and the ability to compare subgroups (e.g., age, race or ethnicity, and gender) would depend on the sampling frame, stratification, and the number of people surveyed.

**Limitations:** A primary limitation is that these data will need to be collected directly by communities. Communities will need to identify through which vehicles data can be gathered. Further, this metric can be sensitive to residential mobility if the same people cannot be followed over time. A community transitioning out residents of poorer health in favor of those who are healthier may appear to be improving the overall health of the community. Therefore, it is important to collect these data along with demographic characteristics to ensure improved health is felt by people of all races and socioeconomic backgrounds. 

<br>

##### PREDICTOR: ACCESS TO AND UTILIZATION OF HEALTH SERVICES 

**Metric: Health professionals shortage area (HPSA) ranking for primary care providers**

This metric denotes that an area has a shortage of primary care providers based on four elements: weighted population-to-provider ratio, share of individuals with incomes below 100 percent of the federal poverty level, infant health index, and travel time or distance to the nearest source of nondesignated accessible care. The Division of Policy and Shortage Designation through the US Department of Health and Human Services calculates a score between 0 to 25 for primary care HPSAs, where the higher the score, the greater the shortage. The facility can get up to 10 points for the population-to-provider ratio, up to 5 for the share of the population with incomes below 100 percent of the federal poverty level, up to 5 for the infant health index (based on infant mortality rate or low birth weight rate), and up to 5 for travel time to the nearest source of care. In identifying a geography as an HPSA, the data managers recommended identifying geographies that contain a designated HPSA of any score to be considered a shortage geography, and those geographies that do not contain a designated HPSA as not having a shortage.

**Validity:** This metric is defined and established by the US Department of Health and Human Services and managed by the Health Resources and Services Administration (HRSA) .

**Availability:** Data for this metric are nationally available by state and county through the US Department of Health and Human Services. 

**Frequency:** Data are updated daily, but geographies and facilities were evaluated at some time in the past four years. 

**Geography:** HPSAs are available by state, county, or service area. Although data are not available at the neighborhood level, individual addresses can be assessed and therefore could be used to derive a value for the neighborhood. Data are available for urban and rural areas. 

**Consistency:** HPSA status can be measured the same way over time and across geographies. The scoring criteria is currently under review and may shift in upcoming years. 

**Subgroups:** This metric can be calculated separately for low-income populations, including migrant farm/seasonal workers, Medicaid-eligible population, and Native American. 

**Limitations:** Even though HPSA status is a characteristic of the local area, some elements used to determine the designation are based on the characteristics of the local population; as such, changing residential mobility patterns may influence this metric. While facilities do not opt-in to be evaluated as an HPSA, localities request to be evaluated as a geographic HPSA or a population-based HPSA. Localities may choose to withdraw as a geographic HPSA in favor of a population-based HPSA (and vice versa) if they believe they may become eligible for more desirable resources. Due to limitations of these data, a binary indicator without additional information on the magnitude of the shortage is being used. Any geography designated as an HPSA (i.e. score >0), we indicate as '1'. Otherwise, a geography is '0', which means it is not an area with a shortage of primary care health professionals.

<br>

##### PREDICTOR: NEONATAL HEALTH 

**Metric: Share of low-weight births**

A child born weighing less than 5 pounds 8 ounces (<2,500 grams) is considered to have a low birthweight. Children born below that threshold are at elevated risk for health conditions and infant mortality. This metric looks at the share of low-birthweight babies out of all births with available birthweight information. 

**Validity:** This metric is the standard currently used by the Centers for Disease Control and Prevention as part of their national assessment on health among infants.

**Availability:** Data on the share of children born with low birthweights are nationally available through the National Center for Health Statistics. 

**Frequency:** Data are updated annually. 

**Geography:** County-level estimates are available through public-use microdata files provided by the National Center for Health Statistics as well as through other data collection efforts, such as the Kids Count Data Center or the CDC WONDER system.

**Consistency:** Medical advances have improved the outcomes for low-birthweight babies, implying this metric may change in the future. However, this has been consistently used over decades as metric for neonatal health. 

**Subgroups:** The share of children born with low birthweights can be broken out by race or ethnicity and mother’s age. 

**Limitations:** Data are not readily available at lower levels of geography, such as neighborhoods, where disparities by race and socioeconomic status within a county are most notable. Large movements of women with risky pregnancies moving in or out of a jurisdiction could influence this metric.

<br>

## Supportive Communities

### Domain: Local Governance {#domain-local-governance}

##### PREDICTOR: POLITICAL PARTICIPATION

**Metric: Share of the voting-eligible population who turn out to vote**

This metric measures the share of the voting-eligible population that voted in the most recent local elections. 

**Validity:** This metric is well established. Scholars of political science have used this metric in articles published in peer-reviewed journals.

**Availability:** Data are reported out by local governments and are available to the public. 

**Frequency:** Data are available at election cycles. 

**Geography:** Data are broadly available even below the city and county levels, at the electoral district level. 

**Consistency:** Voter turnout is measured consistently over time and geography, but the values can be volatile from year to year, with higher turnouts in years involving a presidential election, so comparison over time should account for that. 

**Subgroups:** Voter turnout by race or ethnicity within a jurisdiction can be measured using different methods depending on the demographic balance of the jurisdiction. For diverse or integrated communities, ecological inference or rows by column inference is preferred (King, Rosen, and Tanner 2004; Barreto et al 2019). For less diverse or highly segregated communities, homogenous precinct analysis is preferred (Hajnal and Trounstine 2005). Each is based on the census-defined racial and ethnic characteristics of the jurisdiction.

**Limitations:** Residential mobility can impact this metric, so it is important to interpret changes in voter turnout in the context of demographic shifts in the jurisdiction. In local communities with higher rates of immigrants, voter turnout can inaccurately reflect a community’s political participation. Communities with a population of immigrants who are not registered to vote may consider additional local data to better assess political participation and civic engagement.

<br>

##### PREDICTOR: DESCRIPTIVE REPRESENTATION AMONG LOCAL OFFICIALS

**Metric: The ratio of the share of the city council or county board from specific racial and ethnic groups and the share of city or county residents from those racial or ethnic groups**

This metric measures the ratio of the share of the city council or county board from specific racial and ethnic groups and the share of city or county residents from those racial or ethnic groups. 

**Validity:** Scholars of political science have used this metric in articles published in peer-reviewed journals.

**Availability:** The elements of this metric are available but will need to be combined. Data on the racial or ethnic characteristics of city council or county boards are released publicly by local governments. The racial and ethnic composition of residents in those districts can be calculated using data from the ACS. 

**Frequency:** This metric can be updated as frequently as elections occur.

**Geography:** This can be calculated at the city or county level. 

**Consistency:** This metric can be calculated the same way over time. 

**Subgroups:** This metric accounts for race within its definition. This is also feasible to calculate for other subgroups. 

**Limitations:** Although the movement of people in and out of the jurisdiction can influence this metric, it is likely to be far more sensitive to shifts in the composition of elected officials in the short term. 

<br>

### Domain: Neighborhoods {#domain-neighborhoods}

##### PREDICTOR: ECONOMIC INCLUSION

**Metric: Share of residents experiencing poverty living in high-poverty neighborhoods**

This metric measures the share of a city’s or county’s residents experiencing poverty who live in high-poverty neighborhoods (measured by census tract). A high-poverty neighborhood is one in which over 40 percent of the residents are experiencing poverty. 

**Validity:** Measures of poverty concentration have been widely used to measure the extent and severity of economic exclusion and isolation. The more concentrated and separate people in poverty are from better-resourced neighbors, the more isolated they are from the larger community and the social and economic resources and opportunities it can provide.

**Availability:** Data required to compute poverty concentration are available annually from the Census Bureau’s American Community Survey (ACS).

**Frequency:** This measure can be computed annually.

**Geography:** This measure can be computed for all cities and counties nationwide, although for less populous jurisdictions, it may be necessary to pool data from multiple years of the ACS and report moving averages. Because this metric reflects the structural conditions facing a city or county’s residents, changes in the metric possibly caused by people moving into or out of a jurisdiction do represent changes to those structural conditions. 

**Consistency:** Poverty concentration can be consistently defined and calculated for all cities and counties over time.

**Subgroups:** This metric can be disaggregated separately by race or ethnicity and gender, although in some cases it may be necessary to pool data from multiple years of the ACS and report moving averages.

**Limitations:** This measure can be sensitive to the overall poverty rate of a city or county. Therefore, changes in poverty concentrations need to be assessed with reference to the city or county’s overall poverty rate. 

<br>

##### PREDICTOR: RACIAL DIVERSITY

**Metric: Neighborhood exposure index, or the share of a person’s neighbors who are people of other races and ethnicities**

This metric is constructed separately for each racial or ethnic group and reports the average share of that group’s neighbors who are members of other racial or ethnic groups. For example, the exposure index would report the share of people who are Black and Latinx in the census tract of the average white person, the share of people who are white and Latinx in the census tract of the average Black person, and the share of people who are Black and white in the census tract of the average Latinx person. Higher values of the index indicate more neighborhood diversity and more day-to-day exposure of people to neighbors of different races and ethnicities.

**Validity:** The exposure index is one of several widely used measures of residential segregation or inclusion. It effectively captures the multiracial or multiethnic diversity of American communities today and reflects the experience of individuals of all races and ethnicities, and it provides a comprehensive picture of neighborhood racial and ethnic composition. 

**Availability:** Data required to compute neighborhood exposure indexes are available annually from the ACS. 

**Frequency:** Exposure indexes can be computed annually.

**Geography:** The data are collected annually. For subgroup analyses for less populated areas, it may be necessary to pool several years of data to obtain reliable estimates. Because this metric reflects the structural conditions facing a city or county’s residents, changes in the metric that may be caused by people moving into or out of a jurisdiction do represent changes to those structural conditions. 

**Consistency:** Exposure indexes can be consistently defined and calculated for all cities and counties over time.

**Subgroups:** This metric is by definition disaggregated by race or ethnicity.

**Limitations:** This measure can be sensitive to the overall racial or ethnic composition of a city or county. Therefore, changes in exposure indexes need to be assessed with reference to the city or county’s overall racial or ethnic composition. Further, although this index can be constructed annually, it may take many years to observe appreciable changes. 

<br>

##### PREDICTOR: BELONGINGNESS

**Metric: Inclusion of Other in the Self scale**

This metric is a single-item survey developed by Aron, Aron, and Smollan (1992) that measures how connected the respondent feels with another person or group (e.g., family, neighborhood, school, or community organization). Respondents see seven pairs of circles that range from just touching to almost completely overlapping (1 = no overlap; 2 = little overlap; 3 = some overlap; 4 = equal overlap; 5 = strong overlap; 6 = very strong overlap; 7 = most overlap). One circle in each pair is identified as “self” and the second circle in each pair is labeled “other.” Respondents choose one of the seven pairs to answer the question, “Which picture best describes your relationship with [this person/group]?” The researcher identifies what the person or group for the “other” is being represented. This survey is easily understood by respondents and takes less than one minute to administer (Gachter, Starmer, and Tufano 2015). This metric would require new data collection at the local level. 

**Validity:** Researchers have used the scale to measure belonging with a host of different populations, including 5-year-olds (Cameron et al. 2006), teens, adults, people with low incomes, and formerly incarcerated individuals (Folk et al. 2016; Mashek, Cannaday, and Tangney 2007). In the example of formerly incarcerated individuals, those who felt more belonging in their communities experienced greater residential stability and community readjustment and lower rates of recidivism than less connected individuals (Folk et al 2016). 

**Availability:** This information is not available widely enough in existing data sources to provide coverage at the local level across many geographies.

**Frequency:** The frequency of how often the measure would be collected would depend upon local data collection efforts, but we recommend regular follow-up data collection at least every two years.

**Geography:** The level of geography that the measure would represent (e.g., county, city, or zip code) would depend on the sampling frame, stratification, and the number of people ultimately surveyed to obtain sufficient power for the survey. 

**Consistency:** The degree of consistency in this measure across different places will vary with the extensiveness of the survey design and number of people surveyed in each place. Ideally, the measure could be consistent across some base level of geography (such as the city or county), but some places would likely have more extensive coverage of residents who have taken the survey. 

**Subgroups:** Like geography, the range of subgroups represented and the ability to compare subgroups (e.g., people of color and white people; married and single people; people with children and those without) would depend on the sampling frame, stratification, and the number of people surveyed. 

**Limitations:** The key limitation is the need for local partners to collect representative data. Original data collection may also make benchmarking against other places challenging, depending on the scale and representativeness of data collection in other places. If there is considerable residential turnover in a jurisdiction, this metric might change even if there is no change among those who had been living there.

<br>

##### PREDICTOR: SOCIAL CAPITAL

**Metric: Selected questions from the Social Capital Community Benchmark Survey**

This survey measures the resources provided by a person’s social networks, including both close relations and extended relations, and our metric will use a few items from this survey. The development of the survey builds on the work of Robert D. Putnam (2000) and the strategies for civic revitalization outlined in a report by the Saguaro Seminar (Putnam and Feldstein 2004). The survey collects information on the relative strengths and areas for improvement in communities' civic behavior (Helliwell and Putnam 2004). The metric for social capital is a selection of seven questions from the Social Capital Benchmark Survey covering participation in community organizations, religious attendance, number and racial diversity of friends, engagement with neighborhoods, and the ability to find information on new jobs. These questions provide indicators of generalized social capital, bonding social capital, and bridging social capital at the individual level. No widely available data on social capital exist at the local level, so this metric would require new data collection. 

**Validity:** Measures of social capital have repeatedly been shown to be associated with individual and community well-being and upward mobility (Chetty et al. 2014; Kim, Subramanian, and Kawachi 2006; Putnam 2000; Sampson, Morenoff, and Earls 1999).  However, no standard measure or set of measures exist to capture the relationship between social capital and mobility. To capture both bonding and bridging social capital, we use a set of questions largely drawn from the Social Capital Community Benchmark Survey, developed by Putnam and the Saguaro Seminar at the Harvard Kennedy School.  Though the survey and larger blocks of questions from the survey have been used in peer-reviewed studies before, the smaller subset of questions for this metric has not yet been validated. We anticipate using the initial round of data collection to validate this metric for widespread use and to refine and revise as necessary. 

**Availability:** This information is not widely enough available in existing data sources to provide coverage at the local level across many geographies. To ease data collection, we have attempted to minimize the number of questions needed to measure each of the indicators of social capital (e.g., generalized social capital and bridging and bonding social capital). 

**Frequency:** The frequency of how often the measure would be collected would depend upon local data collection efforts, but we recommend regular follow-up data collection at least every two years. 

**Geography:** The level of geography that the measure would represent (e.g., county, city, or zip code) would depend on the sampling frame, stratification, and the number of people ultimately surveyed to obtain sufficient power for the survey. 

**Consistency:** The degree of consistency in this measure across different places will vary with the extensiveness of the survey design and number of people surveyed in each place. Ideally, the measure could be consistent across some base level of geography (such as the city or county), but some places would likely have more extensive coverage of residents who have taken the survey. 

**Subgroups:** Like geography, the range of subgroups represented and the ability to compare subgroups (people of color and white people; married and single people; people with children and those without) would depend on the sampling frame, stratification, and the number of people surveyed. 

**Limitations:** The key limitation is the need for local partners to collect representative data. Additional limitations include the need to further validate this particular set of questions. Original data collection may also make benchmarking against other places challenging depending on the scale and representativeness of data collection in other places.

<br>

##### PREDICTOR: TRANSPORTATION ACCESS

**Metric: Transit trips index**

This metric reflects the number of public transit trips taken annually at the census tract by a three-person single-parent family with income at 50 percent of the Area Median Income (AMI) for renters. This number is percentile ranked nationally into an index with values ranging from 0 to 100 for each census tract. Higher scores reflect better access to public transportation. 

**Validity:** This metric was designed in partnership with the US Department of Transportation and has been used by the US Department of Housing and Urban Development in community efforts to affirmatively further fair housing. Several scholars have also used this metric and data in published in peer-reviewed journals. Although other arrangements of family composition, income, and housing status are possible in constructing this index and are available in the data, these characteristics were intended to more closely characterize a lower-income household in the community and are the most validated of other household combinations.

**Availability:** The estimates come from the location affordability index, which is publicly available. 

**Frequency:** The location affordability index data are updated every three years.

**Geography:** This can be measured at the census tract or neighborhood level. Values can be averaged at higher levels of geography. For example, one can calculate a population-weighted average value among all census tracts in a county to determine a county-level value.  

**Consistency:** This metric can be calculated the same way over time. 

**Subgroups:** This metric is based on a lower-income population, notably single-parent families earning half the local AMI among renters. 

**Limitations:** This metric cannot alone capture the concept of transportation access. This must be used in partnership with the low transportation cost index to cover geographies that may not have an extensive public transportation system, such as rural areas. 

**Metric: Low transportation cost index**

This index reflects local transportation costs as a share of renters’ incomes. It accounts for both transit and cars. This index is based on estimates of transportation costs for a three-person, single-parent family with income at 50 percent of the median income for renters for the region (i.e., a core-based statistical area). Although other arrangements of family composition, income, and housing status are possible in constructing this index, these characteristics were intended to more closely characterize a lower-income household in the community. Values are inverted and percentile ranked nationally, with values ranging from 0 to 100. The higher the value, the lower the cost of transportation in that neighborhood.

**Validity:** This metric was designed in partnership with the US Department of Transportation and has been used by the US Department of Housing and Urban Development in community efforts to affirmatively further fair housing. Several scholars have also used this metric and data in articles in peer-reviewed journals.

**Availability:** The estimates come from the location affordability index, which are publicly available.

**Frequency:** The location affordability index data are updated every three years.

**Geography:** This can be measured at the census tract or neighborhood level. Values can be averaged at higher levels of geography. For example, one can calculate a population-weighted average value among all census tracts in a county to determine a county-level value.  

**Consistency:** This metric can be calculated the same way over time. 

**Subgroups:** This metric is based on a lower-income population, notably single-parent families earning half the local AMI among renters. 

**Limitations:** Transportation costs may be low for a variety of reasons, including greater access to public transportation and the density of homes, services, and jobs in the neighborhood and surrounding community. It is important not to consider this metric alone but rather in combination with the transit trips index to more fully measure the concept of transportation access. 

<br>

##### PREDICTOR: ENVIRONMENTAL QUALITY

**Metric: Air quality index**

The air quality index  is an index that  summarizes potential exposure to harmful toxins at a neighborhood level. The index is a linear combination of standardized Environmental Protection Agency (EPA) estimates of air quality carcinogenic, respiratory, and neurological hazards at census tracts. Values are inverted and then percentile ranked nationally. Values per census tract range from 0 to 100. The higher the index value, the less exposure to toxins harmful to human health.

**Validity:** EPA scientists and researchers link air pollutants to health effects that can manifest within a few hours or days after breathing polluted air. 

**Consistency:** Air pollutants can be consistently measured over time and space. However, EPA standards may be in flux in the coming years and should be re-evaluated for consistency moving forward. 

**Availability:** Air quality systems data are produced by the US Environmental Protection Agency and are publicly available. 

**Frequency:** Air quality data from the National Air Toxics Assessment (NATA) data were updated every three years since 1996, but the most recent update was in 2014.  

**Geography:** This index is measured at the census tract level and can be rolled up to other levels of geography. 

**Subgroups:** This metric can reflect subgroups by matching  it with demographic characteristics at the census tract, such as racial or ethnic composition or concentrated poverty..  

**Limitations:** Data are not updated with enough frequency. Other data sources can offer information annually, or even daily, but they are at higher levels of geography and would not be able to be disaggregated by subgroups. 

<br>

### Domain: Safety {#domain-safety}

##### PREDICTOR: EXPOSURE TO TRAUMA

**Metric: Adverse Childhood Experiences scale**

The Adverse Childhood Experiences (ACE) scale is a survey-based scale comprising 17 items that measure childhood exposure to trauma such as psychological, physical, or sexual abuse; neglect; mental illness; domestic violence; divorce; and having a parent in prison (Felitti et al. 1998). Each question relates to an experience growing up during the first 18 years of life and solicits a “yes” or “no” response. The number of “yes” answers for each question determines the score, with values from 0 to 17. Higher scores on this scale mean that the respondent has gone through more types of childhood trauma. To construct this metric, community leaders would need to collect data locally. 

**Validity:** A significant body of research finds that that higher ACE scores, indicating more childhood trauma, correlate with several outcomes related to lower mobility. Higher ACE scores are associated with poor performance at work and financial problems as adults (Anda et al. 2004), as well as higher rates of chronic disease, depression, and lower health-related quality of life as adults (Anda et al. 2002; Corso et al. 2008; Felitti et al. 1998). The metric may be most useful as an indicator of need for trauma-informed care at the community level.

**Availability:** This information is not available widely enough in existing data sources to provide coverage at the local level across many geographies.

**Frequency:** The frequency of how often the measure would be collected would depend upon local data collection efforts, but we recommend regular follow-up data collection at least every two years.

**Geography:** The level of geography that the measure would represent (e.g., county, city, or zip code) would depend on the sampling frame, stratification, and the number of people ultimately surveyed to obtain sufficient power for the survey. 

**Consistency:** The degree of consistency in this measure across different places will vary with the extensiveness of the survey design and number of people surveyed in each place. Ideally, the measure would be consistent across some base level of geography (such as the city or county), but some places would likely have more extensive coverage of residents who have completed the ACE scale. 

**Subgroups:** Like geography, the range of subgroups represented and the ability to compare subgroups (people of color and white people; married and single people; people with children and those without) would depend on the sampling frame, stratification, and the number of people surveyed. 

**Limitations:** The key limitation is the need for local partners to collect representative data. Original data collection may also make benchmarking against other places challenging, depending on the scale and representativeness of data collection in other places. This metric may be sensitive to residential mobility because those reporting experiences of trauma in the past may have lived in a different jurisdiction at the time.

<br>

##### PREDICTOR: EXPOSURE TO CRIME 

**Metric: Rates of reported violent crime and property crime**

The FBI’s Uniform Crime Reporting (UCR) Program provides a standard, well-defined measure of crime.  Reported crimes are captured for four “index” violent felonies (murder or nonnegligent manslaughter, rape, robbery, and aggravated assault) and four index property felonies (burglary, larceny-theft, motor vehicle theft, and arson). 

**Validity:** The UCR statistics are the most widely used way to measure and compare reported crime across jurisdictions. The FBI provides definitions for each of the criminal offenses in the index, and most police departments in the United States report the data on those offenses to the FBI through a standardized reporting system.  The purpose of the FBI’s UCR Program is to provide a common language transcending the varying local and state laws. Although there are potential issues with how different departments might classify offenses, UCR is considered the most standardized source. 

**Availability:** The data are available for most jurisdictions across the United States. If a jurisdiction is not included in UCR, local officials may be able to obtain the relevant and comparable data directly from their law enforcement agencies. Data are publicly available for cities with population greater than 10,000 and counties with populations greater than 25,000. For smaller jurisdictions, the FBI collects the data, but access to the data is restricted. 

**Frequency:** Data are, at minimum, reported annually, but they are not broken out by demographic group. Note that the data are reported by law enforcement agencies and would need to be aggregated up to the county level.

**Geography:** The UCR data are available at the city and county level, given the availability noted above. 

**Consistency:** The data are consistent across the jurisdictions that provide data to the FBI, because the FBI establishes the definitions of the crimes included in the index. Data may be accumulated and compiled differently at the local level. 

**Subgroups:** The data include demographic information—age, race, and gender—for those arrested, and for the victims and offenders of homicides only (not for the other crimes in the index). 

**Limitations:** Reporting is not mandatory, and although most jurisdictions provide data, UCR does not capture the universe of reported index crimes across the United States. UCR measures crime reported to the police, so unreported crime is not captured in these data. An FBI analysis estimated that up to half of violent crime goes unreported to the local police (Langton and Berzofsky 2012), and research finds that some neighborhoods are less likely to report violent crime, especially where trust of police is low (Desmond, Papachristos, and Kirk 2016; Goudriaan, Wittebrood, and Nieuwbeerta 2006). As a place-based measure, reported crime is affected by mobility in and out of the jurisdiction. Crime rates are based on the number of incidents per 100,000 residents. If the number of residents increases, the crime rate could go down without any change in the number of reported incidents. Also, crime tends to be concentrated in certain areas. Similarly, if new residents are moving to places where crime rates were already low, the populations and areas experiencing the most crime may also not see any change even if city-wide rates decrease. Relatedly, UCR does not provide data on crime at the neighborhood level, so it cannot track changes in crime or compare different places within a jurisdiction. Multiple law enforcement jurisdictions (e.g., state, county, city, university, tribal) can fall within a single county. Because of this county level, crime counts may be under-estimated in counties where some agency data is missing.

<br>

##### PREDICTOR: EXPOSURE TO OVERLY PUNITIVE POLICING 

**Metric: Rate of juvenile justice arrests**

The FBI’s UCR Program also provides statistics on the number of arrests of people under age 18. Because individuals can be arrested multiple times, the data reports the number of arrests and not individuals. The metric is for juvenile (defined as under 18 years of age and over 9 years of age) arrest for any crime, but the data can be broken down by offense type. Arrest rates can be calculated using population data from the American Community Survey (ACS).

**Validity:** Although arrest behavior of the total population may be confounded by many factors, arrests among juvenile offenders can be more closely tied to overly punitive policing behavior. Research finds that juveniles are more likely to be arrested than adult suspects, after controlling for suspect race, gender, seriousness of offense, and amount of evidence (Brown, Novak, and Frank 2009). Research also finds large and disruptive impacts on adult outcomes; juvenile detention is associated with lower educational attainment, lower rates of employment, and higher rates of criminal offending and incarceration as an adult (Aizer and Doyle 2015). 

**Availability:** Arrest data are available in jurisdictions that report to UCR and are available through the FBI’s Crime Data Explorer tool. The data are available for most jurisdictions across the United States (see the exposure to crime metric for more detail). 

**Frequency:** Juvenile arrest data is available annually through FBI Crime Data Explorer. Arrest data before 2014 can be found on the Bureau of Justice Statistics Arrest Data tool. 

**Geography:** The UCR data are available at the city and county level, for cities with population greater than 10,000 and for counties with population greater than 25,000. 

**Consistency:** The data are consistent across the jurisdictions that provide data to the FBI, because the FBI establishes the definitions of the crimes included in the index and of juvenile as under 18 years of age regardless of state definition. Data may be accumulated and compiled differently at the local level.

**Subgroups:** This metric necessarily measures people within a particular age group but also provides data on age subgroups (e.g. 10–12, 13–15, and 16–17) as well as by race or ethnicity and gender.

**Limitations:** Reporting to UCR is not mandatory, and although most jurisdictions provide data, UCR does not capture the universe of reported index crimes across the United States. These data also do not capture any punitive interactions with school resource officers that do not get elevated to the level of arrest (such as being temporarily detained or being removed or suspended from school). As a place-based measure, reported crime is affected by mobility in and out of the jurisdiction, and because the measure is a rate, large increases or declines in the number of juveniles in an area could also affect the metric.

<br>

## Opportunities to Learn and Earn

### Domain: Education {#domain-education}

##### PREDICTOR: ACCESS TO PRESCHOOL

**Metric: Share of 3- to 4-year-olds enrolled in nursery school or preschool**

This metric measures the share of a jurisdiction’s three- to four-year old children who are enrolled in nursery school or preschool.

**Validity:** Federal agencies such as the National Center for Education Statistics use household survey data to ascertain nursery and preschool enrollment. 

**Availability:** Enrollment data are available annually from the ACS.

**Frequency:** Survey data are collected annually and used to create 1- and 5-year estimates. For subgroup analyses for less populated areas, it may be necessary to pool several years of data to obtain reliable estimates.

**Geography:** Data are available at the county and metro levels.

**Consistency:** Information pertaining to nursery and preschool enrollment in the ACS is measured the same way across all geographies in the same year. Changes to the ACS in the future could influence comparisons over time. 

**Subgroups:** The data can be broken down by race or ethnicity, gender, and other demographic factors. For less populous areas and for certain demographic groups, several years of data may need to be pooled to provide reliable estimates. 

**Limitations:** This metric can change over time if fertility patterns change or if families with young children who move out of or into the jurisdiction have very different propensities for enrolling their children in preschools than parents with young children who remain in the jurisdiction. Because ACS data do not capture the quality of preschool, enrollment figures may overstate exposure to the kinds of programs most likely to improve short-term academic outcomes and long-term outcomes such as mobility from poverty.

<br>

##### PREDICTOR: EFFECTIVE PUBLIC EDUCATION 

**Metric: Average per grade change in English Language Arts achievement between third and eighth grades**

This metric reports the average annual improvement in English (reading comprehension, written expression) observed between the third and eighth grades for each jurisdiction. 

**Validity:** The state assessments are well defined and validated but vary by state. The Stanford Education Data Archive has standardized these to be nationally comparable. Higher rates of improvement in English indicate more effective public education, which improves the upward mobility of children from less advantaged backgrounds. 

**Availability:** Test data are available from the Stanford Education Data Archive and EDFacts.

**Frequency:** The data are collected annually. 

**Geography:** Data are available at the school district and county levels.

**Consistency:** Tests of student progress vary from state to state and can change over time if states modify their tests. The Stanford Education Data Archive has standardized these to be nationally comparable. 

**Subgroups:** The Stanford Education Data Archive has adjusted scores by race or ethnicity and gender, and EDFacts reports proficiency levels based on raw data by race or ethnicity, gender, disability status, limited English proficiency status, homeless status, migrant status, and economically disadvantaged status. 

**Limitations:** Literacy performance reported in “levels” is sensitive to movement in and out of a community over time. States vary in the literacy components included in their state assessments, the rigor of their assessments, and their assessment exemptions.

<br>

##### PREDICTOR: STUDENT POVERTY CONCENTRATION

**Metric: Share of students attending high-poverty schools, by student race or ethnicity**

This set of metrics is constructed separately for each racial or ethnic group and reports the share of students attending schools in which over 40 percent of the student body receives free or reduced-price meals. 

**Validity:** This set of metrics captures the interaction of economic and racial segregation of schools and therefore reveals whether (and to what degree) students of color are more likely than white students to attend schools with large concentrations of classmates experiencing poverty. Higher concentrations of students experiencing poverty are associated with worse achievement for all the students in a school. 

**Availability:** This set of metrics can be constructed using information from the National Center for Education Statistics Common Core of Data. Those data come from an annual census of schools reporting total enrollment by race across each grade including a measure of “economic disadvantage” for students based on their eligibility for free or reduced-price school meals, which is used as a proxy for poverty.

**Frequency:** These metrics can be computed annually.

**Geography:** These metrics can be computed at the school district, city, and county levels. Because this metric reflects the structural conditions facing a city or county’s students, changes in the metric that may result from people moving into or out of a jurisdiction may represent changes to those structural conditions. 

**Consistency:** These metrics can be consistently defined and calculated for all cities and counties.

**Subgroups:** These metrics are by definition disaggregated by race or ethnicity.

**Limitations:** Some school districts convey eligibility to free and reduced-price school meals using community eligibility standards that can apply to clusters of schools as well as entire districts. For example, if a cluster of schools serve a set of low-income neighborhoods, and across the schools, 40 percent or more of the students qualify for free and reduced-price meals, the district can provide meals to all students at all schools in the cluster even if one of the schools wouldn’t meet the threshold on its own. Consequently, this metric may overstate student poverty exposure in those districts. Fortunately, the data sources for this metric allow us to identify the districts using this approach, and findings can be interpreted with this in mind. Further, this measure can be sensitive to the overall racial and ethnic composition of a district, city, or county and its overall poverty rate. Therefore, changes in this metric need to be assessed with reference to the area’s overall racial or ethnic composition. Further, although this metric can be constructed annually, it may take many years to observe appreciable changes.

<br>

##### PREDICTOR: COLLEGE READINESS

**Metric: Share of 19- and 20-year-olds with a high school degree**

This metric is the ratio of the number 19- and 20-year olds with a high school degree in a given jurisdiction to the total number of 19- and 20-year olds in the jurisdiction. 

**Validity:** Earning a high school degree is an important prerequisite for pursuing additional schooling, and although not all high school graduates are ready to enroll in college, high school completion is a well-understood and widely used measure of educational attainment. Data on educational attainment are collected in a variety of federal surveys. 

**Availability:** Data on educational attainment are available annually from the ACS.

**Frequency:** Survey data are collected annually and used to create 1- and 5-year estimates. For subgroup analyses for less populated areas, it may be necessary to pool several years of data to obtain reliable estimates.

**Geography:** Data are available at the county and metro levels.

**Consistency:** Information pertaining to educational attainment in general and on high school graduation, in particular, is measured the same way across all geographies in the same year in the ACS. Changes to the ACS in the future could influence comparisons over time. 

**Subgroups:** The data can be broken down by race or ethnicity, gender, and other demographic factors. For less populous areas and for certain demographic groups, several years of data may need to be pooled to provide reliable estimates. 

**Limitations:** Young adults moving in and out of an area can influence this measure.

<br>

### Domain: Work {#domain-work}

##### PREDICTOR: EMPLOYMENT

**Metric: Employment-to-population ratio for adults ages 25 to 54**

This metric is the ratio of the number of employed adults ages 25 to 54 in a given jurisdiction to the total number of adults in that age range living there. 

**Validity:** Employment captures what share of adults in a jurisdiction are engaging in work for pay. The employment-to-population ratio (EP) is a standard labor market metric reported monthly by the Bureau of Labor Statistics (BLS) and based on the Current Population Survey. The Working Group recommends applying the methodology used to compute the EP to similar data collected in the ACS. 

**Availability:** Data on employment are available from the American Community Survey (ACS).

**Frequency:** Survey data are collected annually and used to create 1- and 5-year estimates. For subgroup analyses for less populated areas, it may be necessary to pool several years of data to obtain reliable estimates.

**Geography:** Data are available at the county and metro levels.

**Consistency:** Information on employment and age is measured the same way across all geographies in the same year in the ACS. It is highly unlikely that the ACS will change how it captures employment in the future. 

**Subgroups:** The data can be broken down by race or ethnicity, gender, and other demographic factors. For less populous areas and for certain demographic groups, several years of data may need to be pooled to provide reliable estimates. 

**Limitations:** The BLS reports the official EP monthly for those age 16 and up as well those age 20 and up. As such, the BLS-reported measure could be lower for jurisdictions that have many young adults attending college rather than working as well as for those that have many retirees. Consequently, for our purposes, we recommend computing the EP for adults ages 25 to 54 using data from the ACS rather than relying on BLS reports. Even when using ACS data, the EP can drop if unemployed people leave an area or if working people move in. The measure can only be computed for the 365 largest counties. 

<br>

##### PREDICTOR: ACCESS TO JOBS PAYING A LIVING WAGE 

**Metric: Ratio of pay on the average job to the cost of living**

This metric shows what a “typical” job pays relative to the cost of living in a particular area. The metric is computed by dividing the average earnings for a job in an area by the cost of meeting a family of three’s basic expenses in that area. 

**Validity:** Jurisdictions in which typical jobs pay a greater share of the local cost of living provide more opportunities for their residents to move out of poverty. Employer reported data on wages paid are a reliable indicator of what jobs pay, and our metric is based on data collected and disseminated by the BLS. Data on what it costs to meet basic expenses requires detailed studies of the cost of food, clothing, shelter, health care, and work-related expenses for each jurisdiction. We rely on the work of well-regarded scholars at the Massachusetts Institute of Technology (MIT) to obtain estimates of the local cost of living. 

**Availability:** Data on wages are available quarterly from the BLS’s Quarterly Census of Employment and Wages, and estimates of the cost of meeting a family’s basic needs, referred to a living wage, are available annually from MIT. 

**Frequency:** The composite data can be computed annually.

**Geography:** Data on wages are available for the 365 largest counties in the US at the county and metro levels. About 75 percent of the US population lives in the 365 largest counties. Data on living wages are available by county.

**Consistency:** Information on weekly wages is collected in a consistent fashion by the BLS. MIT uses a consistent methodology to compute living wages by county. 

**Subgroups:** The data cannot be broken down into subgroups because they describe jobs rather than the people in them.

**Limitations:** The measure cannot be broken down into subgroups. The measure relies on MIT’s computations of “living wages.”
